# Generated by Django 2.0.1 on 2018-01-24 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='thumb',
            field=models.ImageField(blank='true', default='default.png', upload_to=''),
        ),
    ]
