# Generated by Django 2.0.1 on 2018-01-24 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumb',
            field=models.ImageField(blank='true', default='default.jpg', upload_to=''),
        ),
    ]
